<?php
$auto_reviews_en = array(
    array("name" => "Jason W.", "text" => "Very impressed with the material and stitching. Feels amazing all day long."),
    array("name" => "Anthony A.", "text" => "This t-shirt feels like it should cost twice as much. The quality is amazing, and the fit is flattering without being too tight. Great for daily wear or layering. I’ll be stocking up for sure. Matches almost anything."),
    array("name" => "Michael Y.", "text" => "I was skeptical at first, but this t-shirt really impressed me. It holds its shape well, even after multiple washes. Plus, the color hasn’t faded one bit. If you’re on the fence, go for it. My friend bought one too."),
    array("name" => "James G.", "text" => "Wasn't sure at first, but it exceeded my expectations. Will get another one."),
    array("name" => "Charles M.", "text" => "Washed it a few times already and no signs of wear or fading. Happy to find a shirt that actually lasts. Will get another one."),
    array("name" => "Joseph M.", "text" => "Very comfortable t-shirt. I’ve already ordered another one. Matches almost anything."),
    array("name" => "Jeffrey D.", "text" => "Washed it a few times already and no signs of wear or fading. Happy to find a shirt that actually lasts. My friend bought one too."),
    array("name" => "Robert A.", "text" => "Soft fabric and perfect fit. Will buy again. Ideal for hot weather."),
    array("name" => "Jacob C.", "text" => "Very versatile piece. I’ve worn it for workouts, errands, and even layered it under jackets—it just works for everything. Still looks great after washing."),
    array("name" => "Matthew U.", "text" => "This shirt exceeded my expectations in every way. The stitching is top-notch, and it fits like a glove. I've recommended it to a few friends and they're just as happy. A must-have staple in any wardrobe. Perfect for layering."),
    array("name" => "Gary X.", "text" => "Stylish and affordable. Got compliments on it! Wore it to work."),
    array("name" => "Joshua V.", "text" => "Great quality and fits perfectly. I highly recommend it. Feels amazing all day long."),
    array("name" => "Charles T.", "text" => "Good sizing and the neck doesn’t stretch out. Feels amazing all day long."),
    array("name" => "Ryan Q.", "text" => "Stylish and affordable. Got compliments on it! Ideal for hot weather."),
    array("name" => "William M.", "text" => "Very impressed with the material and stitching. Love the texture."),
    array("name" => "Michael P.", "text" => "Soft fabric and perfect fit. Will buy again. Great with jeans."),
    array("name" => "Robert O.", "text" => "Perfect for both casual and semi-formal use. Great with jeans."),
    array("name" => "Paul X.", "text" => "Stylish and affordable. Got compliments on it! Matches almost anything."),
    array("name" => "Andrew E.", "text" => "This t-shirt feels like it should cost twice as much. The quality is amazing, and the fit is flattering without being too tight. Great for daily wear or layering. I’ll be stocking up for sure. My friend bought one too."),
    array("name" => "Ryan X.", "text" => "Soft fabric and perfect fit. Will buy again. Wore it to work."),
    array("name" => "Eric R.", "text" => "Super soft cotton and really nice fit across the shoulders and chest. It’s rare to find something this comfortable with such a clean look. Great with jeans."),
    array("name" => "Andrew Y.", "text" => "After trying many brands, this one finally ticks all the boxes—fit, fabric, durability, and price. Can’t ask for more. Still looks great after washing."),
    array("name" => "James A.", "text" => "A really solid shirt for everyday wear. Ideal for hot weather."),
    array("name" => "Paul J.", "text" => "I was skeptical at first, but this t-shirt really impressed me. It holds its shape well, even after multiple washes. Plus, the color hasn’t faded one bit. If you’re on the fence, go for it. Feels amazing all day long."),
    array("name" => "Jeffrey P.", "text" => "Wasn't sure at first, but it exceeded my expectations. Wore it to work."),
    array("name" => "Mark W.", "text" => "Great value! Fits great and feels amazing. My friend bought one too."),
    array("name" => "Ronald T.", "text" => "Looks good and feels good. Great purchase. Matches almost anything."),
    array("name" => "Charles V.", "text" => "Fabric is soft and breathable, great for summer. Matches almost anything."),
    array("name" => "Gary D.", "text" => "This t-shirt feels like it should cost twice as much. The quality is amazing, and the fit is flattering without being too tight. Great for daily wear or layering. I’ll be stocking up for sure. Will get another one."),
    array("name" => "Paul H.", "text" => "I was genuinely surprised by how good this t-shirt feels. The fabric is soft yet durable, and it doesn't shrink after washing. I've worn it multiple times and it still looks brand new. Definitely worth the purchase! Feels amazing all day long."),
    array("name" => "Jeffrey H.", "text" => "I was genuinely surprised by how good this t-shirt feels. The fabric is soft yet durable, and it doesn't shrink after washing. I've worn it multiple times and it still looks brand new. Definitely worth the purchase! Ideal for hot weather."),
    array("name" => "Daniel W.", "text" => "Fast delivery and excellent packaging. Happy with the product. Still looks great after washing."),
    array("name" => "Mark T.", "text" => "This t-shirt feels like it should cost twice as much. The quality is amazing, and the fit is flattering without being too tight. Great for daily wear or layering. I’ll be stocking up for sure. Feels amazing all day long."),
    array("name" => "Richard A.", "text" => "Very comfortable t-shirt. I’ve already ordered another one. Will get another one."),
    array("name" => "Joseph D.", "text" => "Wasn't sure at first, but it exceeded my expectations. Love the texture."),
    array("name" => "Edward R.", "text" => "Great value! Fits great and feels amazing. Will get another one."),
    array("name" => "Donald P.", "text" => "This t-shirt feels like it should cost twice as much. The quality is amazing, and the fit is flattering without being too tight. Great for daily wear or layering. I’ll be stocking up for sure. Ideal for hot weather."),
    array("name" => "James A.", "text" => "This t-shirt feels like it should cost twice as much. The quality is amazing, and the fit is flattering without being too tight. Great for daily wear or layering. I’ll be stocking up for sure. Great with jeans."),
    array("name" => "James B.", "text" => "The packaging was great and the delivery was faster than expected. I appreciate the attention to detail, even in the stitching. Great with jeans."),
    array("name" => "David O.", "text" => "Fabric is soft and breathable, great for summer. Feels amazing all day long."),
    array("name" => "Richard L.", "text" => "Stylish and affordable. Got compliments on it! Still looks great after washing."),
    array("name" => "Richard F.", "text" => "A really solid shirt for everyday wear. Still looks great after washing."),
    array("name" => "Brian W.", "text" => "Fast delivery and excellent packaging. Happy with the product. Will get another one."),
    array("name" => "Timothy P.", "text" => "Fast delivery and excellent packaging. Happy with the product. Great with jeans."),
    array("name" => "Thomas Q.", "text" => "Great value! Fits great and feels amazing. Still looks great after washing."),
    array("name" => "Eric M.", "text" => "Great quality and fits perfectly. I highly recommend it. Matches almost anything."),
    array("name" => "David O.", "text" => "I was genuinely surprised by how good this t-shirt feels. The fabric is soft yet durable, and it doesn't shrink after washing. I've worn it multiple times and it still looks brand new. Definitely worth the purchase! Will get another one."),
    array("name" => "Timothy P.", "text" => "Looks good even after multiple washes. Will get another one."),
    array("name" => "Matthew W.", "text" => "Excellent value for the price. My new favorite shirt. Will get another one."),
    array("name" => "George S.", "text" => "Washed it a few times already and no signs of wear or fading. Happy to find a shirt that actually lasts. Perfect for layering."),
    array("name" => "William Y.", "text" => "The color is just like in the picture. Love it! Ideal for hot weather."),
    array("name" => "George V.", "text" => "Looks good and feels good. Great purchase. Perfect for layering."),
    array("name" => "David R.", "text" => "Comfortable enough to wear all day long. Will get another one."),
    array("name" => "Edward D.", "text" => "Looks good even after multiple washes. My friend bought one too."),
    array("name" => "Brian A.", "text" => "Super soft cotton and really nice fit across the shoulders and chest. It’s rare to find something this comfortable with such a clean look. Love the texture."),
    array("name" => "Daniel T.", "text" => "After trying many brands, this one finally ticks all the boxes—fit, fabric, durability, and price. Can’t ask for more. Great with jeans."),
    array("name" => "Robert R.", "text" => "Great quality and fits perfectly. I highly recommend it. Still looks great after washing."),
    array("name" => "Joshua P.", "text" => "Very versatile piece. I’ve worn it for workouts, errands, and even layered it under jackets—it just works for everything. Wore it to work."),
    array("name" => "Christopher I.", "text" => "Looks good even after multiple washes. Still looks great after washing."),
    array("name" => "Joshua L.", "text" => "My new go-to shirt for work and weekends. Love the texture."),
    array("name" => "Robert G.", "text" => "After trying many brands, this one finally ticks all the boxes—fit, fabric, durability, and price. Can’t ask for more. Matches almost anything."),
    array("name" => "Mark B.", "text" => "Very versatile piece. I’ve worn it for workouts, errands, and even layered it under jackets—it just works for everything. Love the texture."),
    array("name" => "Joseph M.", "text" => "Great value! Fits great and feels amazing. Ideal for hot weather."),
    array("name" => "Andrew Y.", "text" => "Comfortable enough to wear all day long. Still looks great after washing."),
    array("name" => "Charles G.", "text" => "Fabric is soft and breathable, great for summer. My friend bought one too."),
    array("name" => "Steven L.", "text" => "Very impressed with the material and stitching. My friend bought one too."),
    array("name" => "William J.", "text" => "Fast delivery and excellent packaging. Happy with the product. Wore it to work."),
    array("name" => "Andrew L.", "text" => "Perfect for both casual and semi-formal use. Matches almost anything."),
    array("name" => "Michael Z.", "text" => "Great value! Fits great and feels amazing. Matches almost anything."),
    array("name" => "Joseph D.", "text" => "Perfect for both casual and semi-formal use. Perfect for layering."),
    array("name" => "Richard H.", "text" => "A really solid shirt for everyday wear. Perfect for layering."),
    array("name" => "Robert K.", "text" => "Wasn't sure at first, but it exceeded my expectations. Still looks great after washing."),
    array("name" => "Thomas K.", "text" => "A really solid shirt for everyday wear. Matches almost anything."),
    array("name" => "Ronald A.", "text" => "I was genuinely surprised by how good this t-shirt feels. The fabric is soft yet durable, and it doesn't shrink after washing. I've worn it multiple times and it still looks brand new. Definitely worth the purchase! My friend bought one too."),
    array("name" => "Edward L.", "text" => "The color is just like in the picture. Love it! Perfect for layering."),
    array("name" => "William I.", "text" => "The packaging was great and the delivery was faster than expected. I appreciate the attention to detail, even in the stitching. Still looks great after washing."),
    array("name" => "Christopher Y.", "text" => "Soft fabric and perfect fit. Will buy again. Feels amazing all day long."),
    array("name" => "David M.", "text" => "The packaging was great and the delivery was faster than expected. I appreciate the attention to detail, even in the stitching. Feels amazing all day long."),
    array("name" => "Brian T.", "text" => "Perfect for casual wear or even semi-formal occasions. I've worn it under a blazer and received many compliments. The material is breathable and great for warm days. I'll be getting a few more in different colors. Matches almost anything."),
    array("name" => "Matthew U.", "text" => "Washed it a few times already and no signs of wear or fading. Happy to find a shirt that actually lasts. Great with jeans."),
    array("name" => "Daniel G.", "text" => "I was genuinely surprised by how good this t-shirt feels. The fabric is soft yet durable, and it doesn't shrink after washing. I've worn it multiple times and it still looks brand new. Definitely worth the purchase! Great with jeans."),
    array("name" => "Matthew F.", "text" => "Looks good even after multiple washes. Matches almost anything."),
    array("name" => "Jason G.", "text" => "Perfect for casual wear or even semi-formal occasions. I've worn it under a blazer and received many compliments. The material is breathable and great for warm days. I'll be getting a few more in different colors. Great with jeans."),
    array("name" => "Jeffrey C.", "text" => "The color is just like in the picture. Love it! Great with jeans."),
    array("name" => "Andrew O.", "text" => "Excellent value for the price. My new favorite shirt. Still looks great after washing."),
    array("name" => "Christopher Y.", "text" => "My new go-to shirt for work and weekends. My friend bought one too."),
    array("name" => "Edward Q.", "text" => "I was genuinely surprised by how good this t-shirt feels. The fabric is soft yet durable, and it doesn't shrink after washing. I've worn it multiple times and it still looks brand new. Definitely worth the purchase! Wore it to work."),
    array("name" => "Robert S.", "text" => "Looks good even after multiple washes. Perfect for layering."),
    array("name" => "Nicholas U.", "text" => "Good sizing and the neck doesn’t stretch out. Ideal for hot weather."),
    array("name" => "Joseph D.", "text" => "Good sizing and the neck doesn’t stretch out. Perfect for layering."),
    array("name" => "Michael Y.", "text" => "Perfect for casual wear or even semi-formal occasions. I've worn it under a blazer and received many compliments. The material is breathable and great for warm days. I'll be getting a few more in different colors. Ideal for hot weather."),
    array("name" => "Stephen D.", "text" => "Nice fit and the fabric feels premium. Wore it to work."),
    array("name" => "Charles W.", "text" => "I was skeptical at first, but this t-shirt really impressed me. It holds its shape well, even after multiple washes. Plus, the color hasn’t faded one bit. If you’re on the fence, go for it. Matches almost anything."),
    array("name" => "Ronald P.", "text" => "Great value! Fits great and feels amazing. Perfect for layering."),
    array("name" => "Anthony I.", "text" => "A really solid shirt for everyday wear. Great with jeans."),
    array("name" => "David X.", "text" => "Good quality material, very breathable. Matches almost anything."),
    array("name" => "Daniel N.", "text" => "Nice fit and the fabric feels premium. Matches almost anything."),
    array("name" => "Brian X.", "text" => "Comfortable enough to wear all day long. Wore it to work."),
    array("name" => "James X.", "text" => "Good sizing and the neck doesn’t stretch out. Still looks great after washing."),
    array("name" => "David E.", "text" => "Washed it a few times already and no signs of wear or fading. Happy to find a shirt that actually lasts. Matches almost anything."),
    array("name" => "Ronald J.", "text" => "Nice fit and the fabric feels premium. Feels amazing all day long."),
    array("name" => "Jason T.", "text" => "Wasn't sure at first, but it exceeded my expectations. Matches almost anything."),
    array("name" => "Kevin T.", "text" => "Great quality and fits perfectly. I highly recommend it. Great with jeans."),
    array("name" => "Brian D.", "text" => "Comfortable enough to wear all day long. Ideal for hot weather."),
    array("name" => "Paul O.", "text" => "Looks good and feels good. Great purchase. Ideal for hot weather."),
    array("name" => "Steven M.", "text" => "Good quality material, very breathable. Perfect for layering."),
    array("name" => "Gary Y.", "text" => "This shirt exceeded my expectations in every way. The stitching is top-notch, and it fits like a glove. I've recommended it to a few friends and they're just as happy. A must-have staple in any wardrobe. My friend bought one too."),
    array("name" => "Nicholas J.", "text" => "This t-shirt feels like it should cost twice as much. The quality is amazing, and the fit is flattering without being too tight. Great for daily wear or layering. I’ll be stocking up for sure. Perfect for layering."),
    array("name" => "John W.", "text" => "This shirt exceeded my expectations in every way. The stitching is top-notch, and it fits like a glove. I've recommended it to a few friends and they're just as happy. A must-have staple in any wardrobe. Wore it to work."),
    array("name" => "Charles C.", "text" => "Fast delivery and excellent packaging. Happy with the product. Love the texture."),
    array("name" => "Brian V.", "text" => "Very versatile piece. I’ve worn it for workouts, errands, and even layered it under jackets—it just works for everything. Ideal for hot weather."),
    array("name" => "Ronald O.", "text" => "This shirt exceeded my expectations in every way. The stitching is top-notch, and it fits like a glove. I've recommended it to a few friends and they're just as happy. A must-have staple in any wardrobe. Feels amazing all day long."),
    array("name" => "Timothy H.", "text" => "Looks good and feels good. Great purchase. Great with jeans."),
    array("name" => "Ryan J.", "text" => "Good sizing and the neck doesn’t stretch out. Great with jeans."),
    array("name" => "Jason J.", "text" => "The color is just like in the picture. Love it! Matches almost anything."),
    array("name" => "John J.", "text" => "Looks good and feels good. Great purchase. Feels amazing all day long."),
    array("name" => "Eric E.", "text" => "The color is just like in the picture. Love it! Still looks great after washing."),
    array("name" => "Brian Q.", "text" => "Nice fit and the fabric feels premium. Great with jeans."),
    array("name" => "Robert M.", "text" => "Super soft cotton and really nice fit across the shoulders and chest. It’s rare to find something this comfortable with such a clean look. My friend bought one too."),
    array("name" => "Daniel A.", "text" => "Excellent value for the price. My new favorite shirt. Matches almost anything."),
    array("name" => "Thomas Y.", "text" => "Very comfortable t-shirt. I’ve already ordered another one. Love the texture."),
    array("name" => "Christopher T.", "text" => "Great quality and fits perfectly. I highly recommend it. Ideal for hot weather."),
    array("name" => "Ronald F.", "text" => "Excellent value for the price. My new favorite shirt. Love the texture."),
    array("name" => "Jacob F.", "text" => "Wasn't sure at first, but it exceeded my expectations. Great with jeans."),
    array("name" => "Andrew P.", "text" => "Soft fabric and perfect fit. Will buy again. Love the texture."),
    array("name" => "Jason F.", "text" => "My new go-to shirt for work and weekends. Perfect for layering."),
    array("name" => "Paul O.", "text" => "Stylish and affordable. Got compliments on it! Perfect for layering."),
    array("name" => "Thomas H.", "text" => "Looks good and feels good. Great purchase. Wore it to work."),
    array("name" => "Matthew E.", "text" => "After trying many brands, this one finally ticks all the boxes—fit, fabric, durability, and price. Can’t ask for more. Will get another one."),
    array("name" => "William K.", "text" => "Washed it a few times already and no signs of wear or fading. Happy to find a shirt that actually lasts. Feels amazing all day long."),
    array("name" => "David Y.", "text" => "Excellent value for the price. My new favorite shirt. Ideal for hot weather."),
    array("name" => "Christopher K.", "text" => "Super soft cotton and really nice fit across the shoulders and chest. It’s rare to find something this comfortable with such a clean look. Wore it to work."),
    array("name" => "Michael A.", "text" => "Very comfortable t-shirt. I’ve already ordered another one. Ideal for hot weather."),
    array("name" => "Christopher O.", "text" => "Very impressed with the material and stitching. Wore it to work."),
    array("name" => "Ryan B.", "text" => "Fast delivery and excellent packaging. Happy with the product. Feels amazing all day long."),
    array("name" => "Joseph K.", "text" => "Good sizing and the neck doesn’t stretch out. Matches almost anything."),
    array("name" => "David S.", "text" => "Fabric is soft and breathable, great for summer. Love the texture."),
    array("name" => "Ronald Z.", "text" => "The color is just like in the picture. Love it! Will get another one."),
    array("name" => "Donald L.", "text" => "Super soft cotton and really nice fit across the shoulders and chest. It’s rare to find something this comfortable with such a clean look. Ideal for hot weather."),
    array("name" => "Paul T.", "text" => "After trying many brands, this one finally ticks all the boxes—fit, fabric, durability, and price. Can’t ask for more. Perfect for layering."),
    array("name" => "Gary L.", "text" => "Stylish and affordable. Got compliments on it! Great with jeans."),
    array("name" => "David G.", "text" => "Looks good even after multiple washes. Wore it to work."),
    array("name" => "Thomas U.", "text" => "The color is just like in the picture. Love it! Love the texture."),
    array("name" => "Timothy X.", "text" => "Very comfortable t-shirt. I’ve already ordered another one. My friend bought one too."),
    array("name" => "Daniel Q.", "text" => "Soft fabric and perfect fit. Will buy again. Will get another one."),
    array("name" => "Donald M.", "text" => "After trying many brands, this one finally ticks all the boxes—fit, fabric, durability, and price. Can’t ask for more. Love the texture."),
    array("name" => "Anthony P.", "text" => "Good quality material, very breathable. Will get another one."),
    array("name" => "William L.", "text" => "This shirt exceeded my expectations in every way. The stitching is top-notch, and it fits like a glove. I've recommended it to a few friends and they're just as happy. A must-have staple in any wardrobe. Ideal for hot weather."),
    array("name" => "George R.", "text" => "The color is just like in the picture. Love it! My friend bought one too."),
    array("name" => "William B.", "text" => "Stylish and affordable. Got compliments on it! Will get another one."),
    array("name" => "Gary H.", "text" => "Looks good even after multiple washes. Great with jeans."),
    array("name" => "Brian N.", "text" => "Good quality material, very breathable. Ideal for hot weather."),
    array("name" => "Edward V.", "text" => "My new go-to shirt for work and weekends. Feels amazing all day long."),
    array("name" => "Joseph O.", "text" => "Excellent value for the price. My new favorite shirt. Perfect for layering."),
    array("name" => "Andrew A.", "text" => "Looks good and feels good. Great purchase. Still looks great after washing."),
    array("name" => "Thomas H.", "text" => "Very versatile piece. I’ve worn it for workouts, errands, and even layered it under jackets—it just works for everything. Matches almost anything."),
    array("name" => "Gary P.", "text" => "I was genuinely surprised by how good this t-shirt feels. The fabric is soft yet durable, and it doesn't shrink after washing. I've worn it multiple times and it still looks brand new. Definitely worth the purchase! Matches almost anything."),
    array("name" => "William S.", "text" => "This t-shirt feels like it should cost twice as much. The quality is amazing, and the fit is flattering without being too tight. Great for daily wear or layering. I’ll be stocking up for sure. Wore it to work."),
    array("name" => "Stephen Z.", "text" => "Very impressed with the material and stitching. Ideal for hot weather."),
    array("name" => "Michael G.", "text" => "Washed it a few times already and no signs of wear or fading. Happy to find a shirt that actually lasts. Ideal for hot weather."),
    array("name" => "Mark W.", "text" => "Looks good even after multiple washes. Ideal for hot weather."),
    array("name" => "Daniel L.", "text" => "Excellent value for the price. My new favorite shirt. Great with jeans."),
    array("name" => "Brian D.", "text" => "Stylish and affordable. Got compliments on it! Feels amazing all day long."),
    array("name" => "Joshua F.", "text" => "Wasn't sure at first, but it exceeded my expectations. Perfect for layering."),
    array("name" => "Steven Q.", "text" => "Super soft cotton and really nice fit across the shoulders and chest. It’s rare to find something this comfortable with such a clean look. Still looks great after washing."),
    array("name" => "Michael O.", "text" => "I was skeptical at first, but this t-shirt really impressed me. It holds its shape well, even after multiple washes. Plus, the color hasn’t faded one bit. If you’re on the fence, go for it. Perfect for layering."),
    array("name" => "George Z.", "text" => "Comfortable enough to wear all day long. Great with jeans."),
    array("name" => "Michael Y.", "text" => "Good sizing and the neck doesn’t stretch out. My friend bought one too."),
    array("name" => "Kevin B.", "text" => "Very comfortable t-shirt. I’ve already ordered another one. Perfect for layering."),
    array("name" => "Daniel U.", "text" => "This shirt exceeded my expectations in every way. The stitching is top-notch, and it fits like a glove. I've recommended it to a few friends and they're just as happy. A must-have staple in any wardrobe. Matches almost anything."),
    array("name" => "Ronald T.", "text" => "Great value! Fits great and feels amazing. Great with jeans."),
    array("name" => "Daniel Z.", "text" => "Very versatile piece. I’ve worn it for workouts, errands, and even layered it under jackets—it just works for everything. Feels amazing all day long."),
    array("name" => "Timothy E.", "text" => "The packaging was great and the delivery was faster than expected. I appreciate the attention to detail, even in the stitching. My friend bought one too."),
    array("name" => "Thomas R.", "text" => "Good sizing and the neck doesn’t stretch out. Will get another one."),
    array("name" => "Ryan N.", "text" => "Stylish and affordable. Got compliments on it! Love the texture."),
    array("name" => "Joseph P.", "text" => "The packaging was great and the delivery was faster than expected. I appreciate the attention to detail, even in the stitching. Ideal for hot weather."),
    array("name" => "Timothy X.", "text" => "Looks good and feels good. Great purchase. Love the texture."),
    array("name" => "John O.", "text" => "Soft fabric and perfect fit. Will buy again. My friend bought one too."),
    array("name" => "Charles Y.", "text" => "Soft fabric and perfect fit. Will buy again. Still looks great after washing."),
    array("name" => "Edward N.", "text" => "Soft fabric and perfect fit. Will buy again. Perfect for layering."),
    array("name" => "Andrew T.", "text" => "Good quality material, very breathable. Feels amazing all day long."),
    array("name" => "Richard F.", "text" => "After trying many brands, this one finally ticks all the boxes—fit, fabric, durability, and price. Can’t ask for more. My friend bought one too."),
    array("name" => "Paul B.", "text" => "Soft fabric and perfect fit. Will buy again. Matches almost anything."),
    array("name" => "David B.", "text" => "Good quality material, very breathable. Wore it to work."),
    array("name" => "Joshua W.", "text" => "Great quality and fits perfectly. I highly recommend it. My friend bought one too."),
    array("name" => "Christopher W.", "text" => "Very versatile piece. I’ve worn it for workouts, errands, and even layered it under jackets—it just works for everything. Perfect for layering."),
    array("name" => "Steven W.", "text" => "Perfect for both casual and semi-formal use. Feels amazing all day long."),
    array("name" => "Michael I.", "text" => "Super soft cotton and really nice fit across the shoulders and chest. It’s rare to find something this comfortable with such a clean look. Perfect for layering."),
    array("name" => "Eric O.", "text" => "Comfortable enough to wear all day long. Perfect for layering."),
    array("name" => "Joseph O.", "text" => "The color is just like in the picture. Love it! Wore it to work."),
    array("name" => "Anthony G.", "text" => "The packaging was great and the delivery was faster than expected. I appreciate the attention to detail, even in the stitching. Will get another one."),
    array("name" => "Matthew K.", "text" => "Good quality material, very breathable. Still looks great after washing."),
    array("name" => "Jeffrey Q.", "text" => "Very comfortable t-shirt. I’ve already ordered another one. Still looks great after washing."),
    array("name" => "Nicholas F.", "text" => "Fabric is soft and breathable, great for summer. Wore it to work."),
    array("name" => "Donald G.", "text" => "A really solid shirt for everyday wear. My friend bought one too."),
    array("name" => "Joseph V.", "text" => "After trying many brands, this one finally ticks all the boxes—fit, fabric, durability, and price. Can’t ask for more. Ideal for hot weather."),
    array("name" => "Matthew D.", "text" => "Great value! Fits great and feels amazing. Wore it to work."),
    array("name" => "Daniel X.", "text" => "I was genuinely surprised by how good this t-shirt feels. The fabric is soft yet durable, and it doesn't shrink after washing. I've worn it multiple times and it still looks brand new. Definitely worth the purchase! Perfect for layering."),
    array("name" => "Matthew C.", "text" => "Very impressed with the material and stitching. Will get another one."),
    array("name" => "William O.", "text" => "Perfect for both casual and semi-formal use. Love the texture."),
);
?>