<?php
$auto_reviews_ship = array(
    array("name" => "Martin H.", "text" => "Nemusel som dlho čakať, doručenie prebehlo profesionálne."),
    array("name" => "Peter M.", "text" => "Doručenie bolo mimoriadne rýchle a všetky informácie som dostal e-mailom aj SMS. Obzvlášť sa mi páčilo, že kuriér zavolal pred príchodom. Mal som pocit, že všetko je organizované presne pre zákazníka."),
    array("name" => "Jozef P.", "text" => "Všetko dorazilo načas, kuriér bol veľmi milý."),
    array("name" => "Michal V.", "text" => "Balenie bolo naozaj kvalitné, vidno snahu."),
    array("name" => "Marek K.", "text" => "Balík dorazil nepoškodený a výborne zabalený. Všetko bolo chránené tak, že nehrozilo poškodenie počas prepravy. Veľká pochvala za profesionalitu."),
    array("name" => "Tomáš C.", "text" => "Doručovacia služba bez chyby."),
    array("name" => "Lukáš T.", "text" => "Kuriér bol slušný a ochotný, doručenie presné na minútu. Balík bol úhľadne zabalený a bez poškodenia. Som veľmi spokojný."),
    array("name" => "Róbert T.", "text" => "Veľmi rýchle doručenie a výborná koordinácia."),
    array("name" => "Branislav S.", "text" => "Služba na vysokej úrovni, všetko jasné."),
    array("name" => "Kristián O.", "text" => "Balenie bolo veľmi úhľadné a bezpečné. Žiadne poškodenia a doručenie prišlo v dohodnutom termíne. Len samé pochvaly."),
    array("name" => "Zdenko J.", "text" => "Úhľadne zabalené a bezpečne doručené."),
    array("name" => "Tomáš R.", "text" => "Balík dorazil skôr ako bolo plánované."),
    array("name" => "Ivan B.", "text" => "Všetko dorazilo skôr, než som očakával."),
    array("name" => "Dominik C.", "text" => "Doručenie bolo presné a rýchle."),
    array("name" => "Zdenko U.", "text" => "Doručenie bolo rýchle a balenie veľmi úhľadné. Podpora bola dostupná aj mimo pracovného času. Odporúčam každému, kto chce bezstarostný nákup."),
    array("name" => "Milan C.", "text" => "Obal bol úhľadný a kvalitný."),
    array("name" => "Štefan R.", "text" => "Zákaznícka podpora rýchlo odpovedala na môj dotaz o doručení. Balík dorazil dokonca skôr, než bolo uvedené na stránke. Určite odporúčam."),
    array("name" => "Samuel L.", "text" => "Veľmi jednoduchý proces prevzatia."),
    array("name" => "Tomáš P.", "text" => "Rýchle doručenie a jednoduché prevzatie."),
    array("name" => "Dávid S.", "text" => "Veľmi dobrá služba."),
    array("name" => "Stanislav H.", "text" => "Od objednávky po doručenie všetko prebehlo hladko. Neustále som mal prehľad o stave zásielky, čo vo mne vzbudilo dôveru. Veľmi kvalitná služba."),
    array("name" => "Peter V.", "text" => "Doručenie bolo rýchle."),
    array("name" => "Filip P.", "text" => "Balík dorazil do 2 dní, čo ma veľmi prekvapilo. Balenie bolo kvalitné a úhľadné, presne ako má byť. Určite objednám znova."),
    array("name" => "Andrej F.", "text" => "Všetko prebehlo hladko."),
    array("name" => "Mario D.", "text" => "Balík dorazil skôr než bol predpokladaný termín."),
    array("name" => "Nikolas J.", "text" => "Balík dorazil nepoškodený."),
    array("name" => "Blažej I.", "text" => "Objednanie bolo jednoduché a doručenie ešte jednoduchšie. Informácie o sledovaní boli jasné a aktuálne. Top služba."),
    array("name" => "Ivan K.", "text" => "Nemám žiadne výhrady."),
    array("name" => "Dino A.", "text" => "Doručenie som sledoval online a všetko fungovalo bezchybne. Balík dorazil skôr a bol úhľadne zabalený. Všetky detaily boli dostupné načas."),
    array("name" => "Matej M.", "text" => "Informácie o sledovaní som dostal okamžite."),
    array("name" => "Bojan R.", "text" => "Balenie úhľadné, dorazilo bezpečne a bez poškodenia."),
    array("name" => "Andrej Z.", "text" => "Doručenie bolo rýchlejšie, než bolo uvedené."),
    array("name" => "Dušan G.", "text" => "Podpora vždy dostupná."),
    array("name" => "Vladimír F.", "text" => "Nemal som žiadne problémy, všetko prebehlo hladko."),
    array("name" => "Ivan Z.", "text" => "Zákaznícka podpora bola veľmi ústretová a rýchlo odpovedala. Doručenie prišlo skôr než bolo oznámené. Odporúčam."),
    array("name" => "Alan V.", "text" => "Veľká spokojnosť."),
    array("name" => "Miroslav B.", "text" => "Veľmi rýchle doručenie."),
    array("name" => "Jozef G.", "text" => "Úhľadne zabalené a rýchlo doručené."),
    array("name" => "Matej D.", "text" => "Po objednávke išlo všetko veľmi rýchlo. Balík bol odoslaný v ten istý deň a dorazil už na druhý deň. Výborná skúsenosť."),
    array("name" => "Nino T.", "text" => "Rýchle spracovanie objednávky, výborné."),
    array("name" => "Andrej H.", "text" => "Takto profesionálnu službu vidno len zriedka."),
    array("name" => "Goran J.", "text" => "Objednal som v pondelok a balík prišiel už v stredu. Celý proces bol jednoduchý a prehľadný. Som veľmi spokojný."),
    array("name" => "Nikolas T.", "text" => "Doručenie bolo rýchlejšie než som čakal. Dostával som oznámenia v každej fáze, čo vo mne vzbudilo dôveru. Veľmi profesionálna služba."),
    array("name" => "Alan F.", "text" => "Balík dorazil skôr."),
    array("name" => "Martin Z.", "text" => "Celý proces doručenia bol jednoduchý."),
    array("name" => "Ivan L.", "text" => "Hneď po objednávke som dostal potvrdenie aj číslo na sledovanie. Balík dorazil nepoškodený a načas. Služba si zaslúži jednotku."),
    array("name" => "Kristián N.", "text" => "Balík dorazil v perfektnom stave."),
    array("name" => "Marián D.", "text" => "Len slová chvály – od objednávky po doručenie všetko profesionálne. Kuriér zavolal pred doručením a všetko prebehlo bez stresu. Výborné."),
    array("name" => "Matej R.", "text" => "Sledovanie zásielky fungovalo výborne."),
    array("name" => "Peter L.", "text" => "Balík dorazil úhľadne zabalený a rýchlo doručený."),
    array("name" => "Lukáš F.", "text" => "Všetko prebehlo bez stresu – objednávka, potvrdenie aj doručenie. Balík bol bezpečne zabalený a dorazil načas. Top služba."),
    array("name" => "Štefan O.", "text" => "Všetko prebehlo hladko a rýchlo."),
    array("name" => "Mario E.", "text" => "Oceňujem, že kuriér zavolal pred príchodom. Nemusel som strácať čas, všetko bolo dohodnuté vopred. Veľmi príjemná skúsenosť."),
    array("name" => "René K.", "text" => "Kuriér bol veľmi ústretový."),
    array("name" => "Nikolas B.", "text" => "Všetko prebehlo hladko a úhľadne."),
    array("name" => "Zoran J.", "text" => "Pochvala zákazníckej podpore, rýchlo vyriešili otázku."),
    array("name" => "Dávid L.", "text" => "Kuriér zavolal pred doručením, výborná organizácia."),
    array("name" => "Martin R.", "text" => "Doručovateľ bol milý a profesionálny. Balík dorazil bez problémov. Veľmi pozitívna skúsenosť."),
    array("name" => "Štefan H.", "text" => "Kuriér bol ochotný."),
    array("name" => "Viktor D.", "text" => "Doručenie rýchle a úhľadné."),
    array("name" => "Marián K.", "text" => "Doručenie bolo rýchle a úhľadné, balík bez poškodenia."),
    array("name" => "Boris I.", "text" => "Doručovacia služba výborná."),
    array("name" => "Andrej V.", "text" => "Balík dorazil úhľadne zabalený a bez poškodenia. Obal bol pevný a kvalitný. Vidno dôraz na detaily."),
    array("name" => "Štefan P.", "text" => "Kuriér ma kontaktoval pred doručením."),
    array("name" => "Ivan J.", "text" => "Úhľadne zabalené, veľká pochvala."),
    array("name" => "Damian E.", "text" => "Pochvala za rýchlosť a presnosť."),
    array("name" => "Dušan O.", "text" => "Všetko prebehlo presne podľa popisu."),
    array("name" => "Nikolas H.", "text" => "Všetko úhľadné a presné."),
    array("name" => "Blažej P.", "text" => "Samé pochvaly."),
    array("name" => "Sven K.", "text" => "Všetko výborné."),
    array("name" => "Goran F.", "text" => "Kuriér bol presný a milý."),
    array("name" => "Tomáš Z.", "text" => "Všetko bolo výborné."),
    array("name" => "Mario J.", "text" => "Nemusel som dlho čakať."),
    array("name" => "Slavomír J.", "text" => "Celý proces objednávky a doručenia bol príjemný."),
    array("name" => "Matej C.", "text" => "Doručenie super."),
    array("name" => "Kristián E.", "text" => "Doručenie úhľadné."),
    array("name" => "Ivan M.", "text" => "Všetko bolo transparentné a jasné."),
    array("name" => "Lukáš B.", "text" => "Všetky informácie boli dostupné."),
    array("name" => "Jozef D.", "text" => "Všetky informácie o doručení boli jasné."),
    array("name" => "Nenad B.", "text" => "Balenie pevné a bezpečné, veľká pochvala."),
    array("name" => "Miroslav R.", "text" => "Dorazilo rýchlo."),
    array("name" => "Samuel D.", "text" => "Kuriér bol veľmi korektný."),
    array("name" => "Leon M.", "text" => "Všetko dorazilo úhľadne a načas."),
    array("name" => "Štefan M.", "text" => "Balík dorazil načas."),
    array("name" => "Kristián V.", "text" => "Obal kvalitný, balík nepoškodený."),
    array("name" => "Lovro N.", "text" => "Veľká pochvala za služby."),
    array("name" => "Alan K.", "text" => "Kuriér bol veľmi profesionálny."),
    array("name" => "Ivan T.", "text" => "Obal veľmi kvalitný."),
    array("name" => "Andrej G.", "text" => "Balenie pevné."),
    array("name" => "Marín G.", "text" => "Výborná komunikácia s podporou."),
    array("name" => "Dávid O.", "text" => "Doručenie bolo mimoriadne rýchle."),
    array("name" => "Robert E.", "text" => "Balenie úhľadné a pevné."),
    array("name" => "Filip M.", "text" => "Všetko prebehlo jednoducho a bez komplikácií."),
    array("name" => "Andrej I.", "text" => "Po objednávke som okamžite dostal údaje na sledovanie. Doručenie bolo presné a úhľadné. Výborná organizácia."),
    array("name" => "Martin P.", "text" => "Doručenie rýchle, všetko úhľadne zabalené."),
    array("name" => "Zdenko K.", "text" => "Celý proces doručenia bol veľmi transparentný. Dostával som upozornenia v každej fáze. Bez stresu, všetko funguje výborne."),
    array("name" => "Srečko G.", "text" => "Služba výborná, kuriér veľmi profesionálny."),
    array("name" => "Bruno Z.", "text" => "Všetko dorazilo presne načas."),
    array("name" => "Slavomír P.", "text" => "Doručenie prebehlo hladko. Kuriér bol milý a presný, balík úhľadne zabalený. Veľká spokojnosť."),
    array("name" => "Lukáš J.", "text" => "Rýchle doručenie, milý kuriér a úhľadný balík."),
    array("name" => "Miroslav S.", "text" => "Doručovateľ bol veľmi milý."),
    array("name" => "Andrej K.", "text" => "Všetky fázy doručenia boli jasne komunikované. Balík dorazil skôr a bol dobre zabalený. Veľmi pozitívna skúsenosť."),
    array("name" => "Dominik N.", "text" => "Podpora dostupná aj cez víkend, veľká pochvala."),
    array("name" => "Filip K.", "text" => "Sledovanie zásielky fungovalo perfektne."),
    array("name" => "Lukáš C.", "text" => "Všetko jasné a úhľadné, dorazilo bez meškania."),
    array("name" => "Karol P.", "text" => "Veľmi jednoduché prevzatie."),
    array("name" => "Viktor C.", "text" => "Rýchle a spoľahlivé doručenie."),
    array("name" => "Martin V.", "text" => "Všetko prebehlo bez problémov."),
    array("name" => "Andrej I.", "text" => "Doručenie bolo bezchybné. Kuriér bol veľmi milý a zavolal pred príchodom. Pochvala celému tímu."),
    array("name" => "Lovro C.", "text" => "Všetko dorazilo bez meškania."),
    array("name" => "Robert N.", "text" => "Podpora ma informovala o všetkom."),
    array("name" => "Štefan E.", "text" => "Zvyčajne som skeptický voči recenziám, ale tu všetko sedí."),
    array("name" => "Stanislav T.", "text" => "Nemal som žiadne problémy."),
    array("name" => "Mario L.", "text" => "Balík dorazil nepoškodený a úhľadný."),
    array("name" => "Andrej P.", "text" => "Všetko prebehlo jednoducho a rýchlo. Doručenie načas a bez problémov. Určite odporúčam."),
    array("name" => "Lovro N.", "text" => "Veľká pochvala za služby."),
    array("name" => "Miroslav K.", "text" => "Doručenie bolo veľmi rýchle a kuriér slušný. Balík dorazil v skvelom stave. Odporúčam."),
    array("name" => "Toni H.", "text" => "Veľmi jednoduchý proces objednávky."),
    array("name" => "Vladimír R.", "text" => "Nemusel som dlho čakať, všetko prišlo rýchlo."),
    array("name" => "Marián L.", "text" => "Všetko bolo rýchle a jednoduché. Balík úhľadný, doručenie rýchle a bezpečné. Veľmi pozitívna skúsenosť."),
    array("name" => "Miroslav S.", "text" => "Doručovateľ bol veľmi milý."),
);
?>
