<?php
$auto_reviews_en = array(
    array("name" => "Martin E.", "text" => "Farba zostáva sýta aj po mnohých praniach."),
    array("name" => "Peter H.", "text" => "Tričko Noriks ma naozaj prekvapilo. Látka je na pokožke hladká a strih kopíruje postavu bez toho, aby tlačil. Aj po celom dni nosenia pôsobí stále sviežo."),
    array("name" => "Tomáš V.", "text" => "Vyzerá moderne a luxusne, hoci cena je dostupná."),
    array("name" => "Denis B.", "text" => "Nosím ho každý deň."),
    array("name" => "Kristián L.", "text" => "Najprv som si nebol istý, ale prekonalo moje očakávania. Kúpim si ďalšie."),
    array("name" => "Viktor I.", "text" => "Minimalistický dizajn, hodí sa ku všetkému."),
    array("name" => "Marek S.", "text" => "Aj po desiatich praniach vyzerá ako nové."),
    array("name" => "Nikolas H.", "text" => "Nie je vidieť pot."),
    array("name" => "Martin U.", "text" => "Sadne štíhlym aj robustnejším postavám."),
    array("name" => "Andrej P.", "text" => "Noriks sa stal mojím štandardom na každý deň. Mäkké, ale pevné a drží tvar. Veľkosť sedí presne podľa tabuľky."),
    array("name" => "Matej K.", "text" => "Látka je ľahká, ale nepriehľadná."),
    array("name" => "Dávid Z.", "text" => "Veľmi pohodlné tričko. Už som objednal ďalšie. Hodí sa takmer ku všetkému."),
    array("name" => "Lukáš I.", "text" => "Hodí sa ku každej farbe."),
    array("name" => "Ivan L.", "text" => "Dostatočne dlhé, aby zostalo v nohaviciach."),
    array("name" => "Blažej H.", "text" => "Látka nedráždi pokožku ani pri potení."),
    array("name" => "Toni J.", "text" => "Na šport aj do mesta."),
    array("name" => "Zoran G.", "text" => "Mäkký, ale odolný materiál."),
    array("name" => "Štefan T.", "text" => "Na prvý pohľad vidno, že nepôsobí lacno."),
    array("name" => "Boris C.", "text" => "Jednoduché, ale moderné."),
    array("name" => "Daniel P.", "text" => "Dostal som viac, než som očakával."),
    array("name" => "Miroslav U.", "text" => "Mal som ho na cestách – nepokrčilo sa ani po hodinách v kufri."),
    array("name" => "Ivan R.", "text" => "Super ľahké a pohodlné."),
    array("name" => "Tomáš L.", "text" => "Nosím ho k saku aj k teplákom."),
    array("name" => "Nikola O.", "text" => "Farba vydrží dlho."),
    array("name" => "Martin E.", "text" => "Už ich mám päť."),
    array("name" => "Goran T.", "text" => "Má štýl aj funkčnosť."),
    array("name" => "Mario M.", "text" => "Pôsobí prémiovo už na dotyk."),
    array("name" => "Róbert L.", "text" => "Vyzerá mužsky a elegantne."),
    array("name" => "Andrej J.", "text" => "Nosím ho skoro každý druhý deň."),
    array("name" => "Nikolas T.", "text" => "Mäkké ako bavlna, ale odolnejšie."),
    array("name" => "Alan M.", "text" => "Materiál je mäkký a ani po viacerých praniach sa nevytiahne. Klobúk dole!"),
    array("name" => "Filip P.", "text" => "Noriks si ma získal už pri prvom nosení. Je priedušné a nelepí sa na pokožku. Strih vyzerá dobre k rifliam aj chino nohaviciam."),
    array("name" => "Bruno L.", "text" => "Správna dĺžka rukávov."),
    array("name" => "Gordon F.", "text" => "Dlho som hľadal takýto model. Ďakujem!"),
    array("name" => "Kristián B.", "text" => "Veľmi odolné voči opotrebovaniu – stále vyzerá ako nové."),
    array("name" => "Tomáš T.", "text" => "Luxusné na dotyk."),
    array("name" => "Peter N.", "text" => "Výborne vyzerá s bundou."),
    array("name" => "Martin V.", "text" => "Pral som ho už viackrát a stále bez známok opotrebenia. Určite kúpim ďalšie."),
    array("name" => "Igor N.", "text" => "Nepokrčí sa ani po celom dni."),
    array("name" => "Nenad U.", "text" => "Farba vyzerá ešte lepšie naživo."),
    array("name" => "Sven Z.", "text" => "Ľahko sa žehlí."),
    array("name" => "Zdenko Z.", "text" => "Som nadšený! Splnilo všetko, čo som hľadal."),
    array("name" => "Adrián L.", "text" => "Hodí sa ku každým nohaviciam."),
    array("name" => "Andrej F.", "text" => "Sedí aj keď som medzi veľkosťami."),
    array("name" => "Ivan K.", "text" => "Perfektná veľkosť."),
    array("name" => "Željko G.", "text" => "Ideálne tričko pre moderného muža – nič navyše, všetko akurát."),
    array("name" => "Dino M.", "text" => "Klasika s nádychom štýlu."),
    array("name" => "Marek A.", "text" => "Športový nádych s elegantným finišom – skvelá kombinácia."),
    array("name" => "Mario H.", "text" => "Do práce aj na voľný čas."),
    array("name" => "Lukáš I.", "text" => "Nikde netlačí ani pod pazuchami."),
    array("name" => "Ivan M.", "text" => "Strih perfektný aj pre vysokých."),
    array("name" => "Štefan K.", "text" => "Našiel som nové obľúbené tričko."),
    array("name" => "Bojan S.", "text" => "Ideálne na cestovanie – ľahké a skladné."),
    array("name" => "František C.", "text" => "Mal som ho na pohovore – cítil som sa sebavedomo."),
    array("name" => "Tomáš H.", "text" => "Perfektná dĺžka a strih."),
    array("name" => "Nikola G.", "text" => "Nosím ho do práce aj do mesta."),
    array("name" => "Vladimír G.", "text" => "Elegantné a pohodlné."),
    array("name" => "Jozef L.", "text" => "Perfektná rovnováha medzi eleganciou a pohodlím."),
    array("name" => "Lukáš T.", "text" => "Skvelé na tréning aj každodenné nosenie."),
    array("name" => "Ivan J.", "text" => "Kvalita nad cenou."),
    array("name" => "Leon Z.", "text" => "Drží tvar aj farbu."),
    array("name" => "Blažej E.", "text" => "Dá sa ľahko zladiť aj na formálnejší outfit."),
    array("name" => "Martin T.", "text" => "Dostal som veľa komplimentov."),
    array("name" => "Kristián H.", "text" => "Nezachytáva chĺpky."),
    array("name" => "Tibor V.", "text" => "Drží celý deň."),
    array("name" => "Filip Z.", "text" => "Tričko na každú príležitosť."),
    array("name" => "Dražen V.", "text" => "Pohodlné celý deň."),
    array("name" => "Miroslav D.", "text" => "Minimalistický a mužný dizajn."),
    array("name" => "Samuel O.", "text" => "Funguje na každý deň."),
    array("name" => "Róbert G.", "text" => "Najlepšie, čo som kúpil online."),
    array("name" => "Andrej G.", "text" => "Moja prvá voľba každé ráno."),
    array("name" => "Martin L.", "text" => "Sedí ako uliate."),
    array("name" => "Kristián V.", "text" => "Strih Noriks trička je výborne navrhnutý. Kopíruje postavu, ale netlačí ani v ramenách ani v páse."),
    array("name" => "Alan W.", "text" => "Vyzerá drahšie, než v skutočnosti je."),
    array("name" => "Emil W.", "text" => "Pôsobí prémiovo."),
    array("name" => "Viktor U.", "text" => "Látka je mäkká a neukazuje známky nosenia."),
    array("name" => "Tibor E.", "text" => "Rukávy nie sú príliš úzke."),
    array("name" => "Peter M.", "text" => "Dlho som nebol tak spokojný s obyčajným tričkom."),
    array("name" => "Dominik T.", "text" => "Na prechádzky aj večerné výjazdy."),
    array("name" => "Bruno K.", "text" => "Nedeformuje sa."),
    array("name" => "Andrej I.", "text" => "Najpohodlnejšie tričko tejto sezóny. Dýcha a nikde netlačí."),
    array("name" => "Stanislav P.", "text" => "Len čakám, kedy uschne, aby som ho mohol znovu nosiť."),
    array("name" => "Karol U.", "text" => "Casual štýl, ktorý mám rád."),
    array("name" => "Nikolas Z.", "text" => "Výborný pomer ceny a kvality."),
    array("name" => "Fabian R.", "text" => "Ľahko sa nekrčí, čo oceňujem."),
    array("name" => "Zlatko F.", "text" => "Konečne niečo moderné a pohodlné zároveň."),
    array("name" => "Martin P.", "text" => "Vyzerá upravene aj po celom dni nosenia."),
    array("name" => "Jozef X.", "text" => "Ľahké na leto, vhodné aj na vrstvenie."),
    array("name" => "Vladimír K.", "text" => "Stalo sa mojím obľúbeným."),
    array("name" => "Erik J.", "text" => "Vyzerá ešte lepšie naživo než na fotkách."),
    array("name" => "Tomáš S.", "text" => "Špeciálny vzhľad aj pocit."),
    array("name" => "Karol Z.", "text" => "Rovnako dobré aj pod sveter."),
    array("name" => "Zvonimir N.", "text" => "Nezošmykuje sa z ramien."),
    array("name" => "Ivan D.", "text" => "Pohodlné a zároveň profesionálne."),
    array("name" => "Nino G.", "text" => "Tričko zostáva svieže aj po celom dni pohybu."),
    array("name" => "Lovro M.", "text" => "Konečne tričko vhodné aj pre vyšších ľudí."),
    array("name" => "Boris T.", "text" => "Tak pohodlné, že je ako pyžamo."),
    array("name" => "Filip K.", "text" => "Skvelá dĺžka – nevytŕča z nohavíc."),
    array("name" => "Tomáš J.", "text" => "Rýchlo schne, ideálne na cestovanie."),
    array("name" => "Štefan M.", "text" => "Nielen skvelo vyzerá, ale aj pôsobí, akoby som nič nemal na sebe."),
    array("name" => "Goran V.", "text" => "Ak hľadáte spoľahlivé tričko, toto je ono."),
    array("name" => "Dávid I.", "text" => "Praktické a moderné – čo viac chcieť?"),
    array("name" => "Željko B.", "text" => "Každý outfit s ním vyzerá lepšie."),
    array("name" => "Neven D.", "text" => "Moja priateľka mu dala 5 z 5 – to hovorí za všetko."),
    array("name" => "Vedran G.", "text" => "Po každom praní vyzerá ako nové."),
    array("name" => "Ivan Z.", "text" => "Stalo sa súčasťou môjho každodenného outfitu."),
    array("name" => "Kristián D.", "text" => "Perfektný balans medzi športovým a elegantným."),
    array("name" => "Miroslav R.", "text" => "Drží tvar aj farbu, strih je ideálny."),
    array("name" => "Matej V.", "text" => "Strih pekne sedí v páse aj ramenách."),
    array("name" => "Filip F.", "text" => "Po praní nemení tvar."),
    array("name" => "Alan C.", "text" => "Farba zostala rovnaká aj po mnohých praniach."),
    array("name" => "Kristián P.", "text" => "Strih kopíruje postavu, ale je pohodlný."),
    array("name" => "Blažej K.", "text" => "Sadne aj širším ramenám."),
    array("name" => "Tomáš G.", "text" => "Odolné aj pri športe."),
    array("name" => "Andrej N.", "text" => "Výborne dýcha aj počas náročného pracovného dňa."),
    array("name" => "Andrej K.", "text" => "Materiál pôsobí kvalitne a ľahko sa kombinuje."),
    array("name" => "Samuel R.", "text" => "Prešlo testom 12 hodín v práci."),
    array("name" => "Ivan N.", "text" => "Takéto tričko som hľadal roky."),
    array("name" => "Dominik R.", "text" => "Hodí sa ku všetkému."),
    array("name" => "Lukáš W.", "text" => "Super alternatíva ku košeli."),
    array("name" => "Emil T.", "text" => "Ideálne riešenie na každý deň."),
    array("name" => "Róbert N.", "text" => "Drží kvalitu aj po mesiaci prania."),
    array("name" => "Martin Q.", "text" => "Ani po celom dni netlačí."),
    array("name" => "Kristián J.", "text" => "Skvelé do práce aj na voľný čas."),
    array("name" => "Jozef E.", "text" => "Sedí perfektne."),
    array("name" => "Željko F.", "text" => "Aj po viacerých noseniach vyzerá ako nové."),
    array("name" => "Dávid W.", "text" => "Pohodlné v každej polohe."),
    array("name" => "Lukáš B.", "text" => "Nosím ho každý deň."),
    array("name" => "Krištof D.", "text" => "Vyzerá ako šité na mieru."),
    array("name" => "Stanislav G.", "text" => "Pri potení nezanecháva škvrny."),
    array("name" => "Branislav V.", "text" => "Nevyťahuje sa po praní."),
    array("name" => "Damian S.", "text" => "Výborné na vrstvenie."),
    array("name" => "Andrej V.", "text" => "Sviežosť vydrží celý deň."),
    array("name" => "Toni L.", "text" => "Príjemné aj na slnku."),
    array("name" => "Nikolas L.", "text" => "Dostal som veľa komplimentov."),
    array("name" => "Boris M.", "text" => "Recenzie nepíšem často, ale tu som musel – nadšenie."),
    array("name" => "Marián K.", "text" => "Ľahko sa perie a rýchlo schne."),
    array("name" => "Goran S.", "text" => "Detaily pri krku sú veľmi kvalitne spracované."),
    array("name" => "Ivan Z.", "text" => "Súčasť každodenného outfitu."),
    array("name" => "Bruno G.", "text" => "Vyzerá ako nové aj po dlhšom čase."),
    array("name" => "Viktor C.", "text" => "Strih lichotí postave a látka nie je priehľadná."),
    array("name" => "Filip O.", "text" => "Služba výborná."),
    array("name" => "Zdenko D.", "text" => "Kúpil som jedno a hneď objednal ďalšie tri."),
    array("name" => "Tomáš P.", "text" => "Pohodlné aj po celom dni."),
    array("name" => "Štefan P.", "text" => "Dostatočne elastické."),
    array("name" => "Miroslav S.", "text" => "Vyzerá upravene aj po praní."),
    array("name" => "Viktor I.", "text" => "Neprilepí sa ani keď sa spotím."),
    array("name" => "Andrej R.", "text" => "Jednoducho perfektné."),
    array("name" => "Lovro R.", "text" => "Najpohodlnejšie tričko, aké mám."),
    array("name" => "Nikolas A.", "text" => "Dobré aj v zime pod mikinu."),
    array("name" => "Marek E.", "text" => "Odporúčania boli pravdivé."),
    array("name" => "Andrej J.", "text" => "Dobrá investícia."),
    array("name" => "Martin H.", "text" => "Ukázalo mi, aký rozdiel robí dobrý strih."),
    array("name" => "Blažej P.", "text" => "Veľká pochvala."),
    array("name" => "Miroslav Z.", "text" => "Strih okamžite pôsobí upravenejšie."),
    array("name" => "Filip B.", "text" => "Neuverteľne pohodlné."),
    array("name" => "Kristián E.", "text" => "Látka je hladká a príjemná na pokožke."),
    array("name" => "Marin D.", "text" => "Nezachytáva prach ani chlpy."),
    array("name" => "Ivan D.", "text" => "Ideálne pre tých, čo chcú pohodlie aj štýl."),
    array("name" => "Krištof N.", "text" => "Ani na slnku mi nebolo horúco."),
    array("name" => "Mario K.", "text" => "Moderný, ale nie prehnaný strih."),
    array("name" => "Željko E.", "text" => "Recenzie tentokrát neklamali."),
    array("name" => "Stanislav H.", "text" => "Pohodlné a čistý vzhľad."),
    array("name" => "Damian V.", "text" => "Nosím ho do práce aj večer von."),
    array("name" => "Božidar J.", "text" => "Žiadne zbytočné logá – konečne."),
    array("name" => "Daniel K.", "text" => "Spojenie pohodlia a elegantného vzhľadu."),
    array("name" => "Jakub P.", "text" => "Hneď som objednal ďalšie dve."),
    array("name" => "Leon F.", "text" => "Jemný lesk pôsobí elegantne."),
    array("name" => "Gordon J.", "text" => "Strih zvýrazní postavu bez nepohodlia."),
    array("name" => "Viktor R.", "text" => "Dlho som nebol tak spokojný s online nákupom."),
    array("name" => "Tibor B.", "text" => "Perfektné tričko na každý deň."),
    array("name" => "Miroslav K.", "text" => "Výborný pocit na pokožke a presná veľkosť."),
    array("name" => "Andrej V.", "text" => "Spoľahlivá kvalita každý týždeň."),
    array("name" => "Martin C.", "text" => "Stojí za každé euro."),
    array("name" => "Tomáš N.", "text" => "Prežije práčku aj sušičku bez problémov."),
    array("name" => "Boris U.", "text" => "Mám ho vo viacerých farbách."),
    array("name" => "Alan T.", "text" => "Prvý dojem? Wow."),
    array("name" => "Štefan H.", "text" => "Golier drží tvar aj po praní."),
    array("name" => "Dino E.", "text" => "Najlepšie tričko, aké som kúpil."),
    array("name" => "Andrej H.", "text" => "Presne to, čo som hľadal."),
    array("name" => "Filip L.", "text" => "Výborné spracovanie."),
    array("name" => "Kristián T.", "text" => "Ľahké, ale odolné."),
    array("name" => "Marián O.", "text" => "Taký pocit slobody som ešte nemal."),
    array("name" => "Peter B.", "text" => "Skvelé aj vo vlhku."),
    array("name" => "František D.", "text" => "Kúpil som viac kusov."),
    array("name" => "Nikola M.", "text" => "Elastické a pohodlné."),
    array("name" => "Ivan R.", "text" => "Výborné v lete aj zime."),
    array("name" => "Mario F.", "text" => "Vyzerá dostatočne profesionálne."),
    array("name" => "Željko C.", "text" => "Zvládne aj náročné nosenie."),
    array("name" => "Vladimír F.", "text" => "Neztráca tvar ani po praní."),
    array("name" => "Andrej J.", "text" => "Lepšie než mnohé drahšie značky."),
    array("name" => "Lukáš V.", "text" => "Drží pevnosť celý deň."),
    array("name" => "Nikolas V.", "text" => "Vyzerá ako nové aj po mesiacoch."),
    array("name" => "Kristián N.", "text" => "Skvelá hustota látky."),
    array("name" => "Božidar C.", "text" => "Sadlo hneď bez úprav."),
    array("name" => "Zdenko U.", "text" => "Perfektný strih pre moju postavu."),
    array("name" => "Miroslav S.", "text" => "Doručovateľ bol veľmi milý."),
    array("name" => "Goran J.", "text" => "Hodí sa k teniskám aj topánkam."),
    array("name" => "Krištof Y.", "text" => "Cítim sa v ňom sebavedome."),
    array("name" => "Vedran F.", "text" => "Perfektné tričko na každý deň."),
    array("name" => "Dávid O.", "text" => "Ľahké, ale drží líniu."),
    array("name" => "Nikola H.", "text" => "Golier zostáva rovný."),
    array("name" => "Tibor G.", "text" => "Vedela som, že objednám znova."),
    array("name" => "Angelo M.", "text" => "Textúra ma nadchla."),
    array("name" => "Róbert T.", "text" => "Veľmi rýchle doručenie."),
    array("name" => "Nikola J.", "text" => "Perfektne sedí v ramenách."),
    array("name" => "Andrej P.", "text" => "Najlepší pomer ceny a kvality."),
    array("name" => "Alan J.", "text" => "Ako šité na mieru."),
    array("name" => "František E.", "text" => "Farba ešte lepšia naživo."),
    array("name" => "Lovro V.", "text" => "Mäkké a pevné zároveň."),
    array("name" => "Marin K.", "text" => "Mäkké a odolné."),
    array("name" => "Filip T.", "text" => "Žiadne švy, ktoré by dráždili."),
    array("name" => "Sven R.", "text" => "Kúpil som jedno a potom ďalšie tri."),
    array("name" => "Igor T.", "text" => "Strih zvýrazňuje ramená."),
    array("name" => "Daniel E.", "text" => "Jedno z mála tričiek, ktoré mi sedí."),
    array("name" => "Andrej I.", "text" => "Univerzálne do fitka aj kancelárie."),
    array("name" => "Željko O.", "text" => "Vyzerá upravene aj po sedení."),
    array("name" => "Alan V.", "text" => "Čierna verzia vyzerá fantasticky."),
    array("name" => "Nikolas B.", "text" => "Perfektný balans casual a smart."),
    array("name" => "Milan C.", "text" => "Nevytvára žmolky."),
    array("name" => "Mario D.", "text" => "Okamžite favorit v šatníku."),
    array("name" => "Tomáš R.", "text" => "Rýchlo schne — ideálne na cestovanie."),
    array("name" => "Zvonimir T.", "text" => "Jednoduché bez zbytočností."),
    array("name" => "Boris T.", "text" => "Tak pohodlné, že naň zabúdam."),
    array("name" => "Željko M.", "text" => "Spoľahlivá voľba na každý deň."),
    array("name" => "Dávid B.", "text" => "Ľahké, nepriehľadné a pohodlné."),
    array("name" => "Ivan T.", "text" => "Veľkosť L sedí perfektne."),
    array("name" => "Stanislav P.", "text" => "Skvelý fit a pohodlie."),
    array("name" => "Peter V.", "text" => "Najlepšie tričko v tejto cenovej kategórii."),
    array("name" => "Viktor D.", "text" => "Vyzerá dobre celý deň."),
    array("name" => "Nino T.", "text" => "Výborné aj v horúčavách."),
    array("name" => "Željko B.", "text" => "Pozdvihne každý outfit."),
    array("name" => "Andrej V.", "text" => "Zostáva svieže celý deň."),
    array("name" => "Viktor K.", "text" => "Vyzerá drahšie než stojí."),
    array("name" => "Dávid L.", "text" => "Príjemné na pokožke."),
    array("name" => "René K.", "text" => "Čistý moderný strih."),
    array("name" => "Darko A.", "text" => "Nestráca tvar."),
    array("name" => "Miroslav G.", "text" => "Ľahko kombinovateľné."),
    array("name" => "Lukáš C.", "text" => "Biela verzia nie je priehľadná."),
    array("name" => "Kristián O.", "text" => "Okraje zostávajú rovné."),
    array("name" => "Štefan Z.", "text" => "XXL sedí lepšie než iné značky."),
    array("name" => "Stanislav T.", "text" => "Látka dýcha aj v teple."),
    array("name" => "Andrej M.", "text" => "Skvelé na každodenné nosenie."),
    array("name" => "Martin N.", "text" => "Vidno dôraz na detaily."),
    array("name" => "Jakub R.", "text" => "Nezráža sa ani v sušičke."),
    array("name" => "Krištof W.", "text" => "Jemne zúžené, ale pohodlné."),
    array("name" => "Toni F.", "text" => "Prémiová kvalita."),
    array("name" => "Vedran R.", "text" => "Jednoduché a zároveň prémiové."),
    array("name" => "Mario J.", "text" => "Perfektná hrúbka látky."),
    array("name" => "Ivan B.", "text" => "Jedno tričko na všetko."),
    array("name" => "Róbert E.", "text" => "Švy sú precízne."),
    array("name" => "Milan P.", "text" => "Vyzerá sviežo aj po častom nosení."),
    array("name" => "Kristián Y.", "text" => "Tmavozelená vyzerá skvele."),
    array("name" => "Željko H.", "text" => "Veľkosť M ideálna."),
    array("name" => "Filip M.", "text" => "Všetko prebehlo jednoducho."),
    array("name" => "Tvrtko S.", "text" => "Vyzerá ako prémiová značka bez vysokej ceny."),
    array("name" => "Alan J.", "text" => "Ako šité na mieru."),
    array("name" => "Vladimír C.", "text" => "Prišlo rýchlo a okamžite nadšenie."),
    array("name" => "Dávid I.", "text" => "Na víkend aj večeru."),
    array("name" => "Karol M.", "text" => "Perfektné pre citlivú pokožku."),
    array("name" => "František P.", "text" => "Ani po celom dni nezapácha."),
    array("name" => "Zoran L.", "text" => "Opticky rozširuje ramená."),
    array("name" => "Dávid I.", "text" => "Praktické doma aj v práci."),
    array("name" => "Igor S.", "text" => "Objednávka jednoduchá a prehľadná."),
    array("name" => "Andrej D.", "text" => "Biela a tmavomodrá sú perfektná kombinácia."),
    array("name" => "Andrej K.", "text" => "Cítim sa v ňom sebavedomejšie."),
    array("name" => "Miroslav N.", "text" => "Po sušení netreba žehliť."),
    array("name" => "Goran P.", "text" => "Švy sú zvnútra mäkké."),
    array("name" => "Željko D.", "text" => "Moje go-to tričko do práce."),
    array("name" => "Ivan G.", "text" => "Nevytvára žmolky."),
    array("name" => "Leo C.", "text" => "Farba presne ako na obrázku."),
    array("name" => "Damian P.", "text" => "Pôsobí ako drahší kus."),
    array("name" => "Ervín S.", "text" => "Mäkké a pevné už na dotyk."),
    array("name" => "Srečko G.", "text" => "Výborná služba."),
    array("name" => "Viktor M.", "text" => "Odolné aj pri intenzívnom nosení."),
    array("name" => "Nikola V.", "text" => "Nezostávajú škvrny."),
    array("name" => "Štefan O.", "text" => "XL sedí presne."),
    array("name" => "Borna R.", "text" => "Ideálne pre minimalistov."),
    array("name" => "Andrej Š.", "text" => "Od fitka po kaviareň."),
    array("name" => "Miroslav P.", "text" => "Sivá vyzerá veľmi elegantne."),
    array("name" => "Filip G.", "text" => "Pohodlné aj na dlhé cestovanie."),
    array("name" => "Ivan Y.", "text" => "Odporúčam každému."),
    array("name" => "Karol P.", "text" => "Drží formu aj pod košeľou."),
    array("name" => "Matej D.", "text" => "Vyzeráš dobre bez námahy."),
    array("name" => "Emil C.", "text" => "Jednoducho perfektné. Vzal som všetky farby.")
);
?>
