<?php
$auto_reviews_en = array(
    array("name" => "Martin M.", "text" => "Farba boxeriek zostáva rovnaká aj po mnohých praniach, nič nebledne."),
    array("name" => "Róbert P.", "text" => "Boxerky Noriks ma naozaj prekvapili. Látka je mäkká, nedráždi pokožku a netlačí tam, kde nemá."),
    array("name" => "Marek S.", "text" => "Naozaj pohodlné boxerky na celý deň, ani o nich neviem."),
    array("name" => "Tomáš R.", "text" => "Guma v páse je pevná, ale netlačí. Nezarezáva sa do kože."),
    array("name" => "Jozef D.", "text" => "Priedušné a ľahké, ideálne do práce aj do fitka."),
    array("name" => "Lukáš M.", "text" => "Boxerky držia tvar aj po viacerých praniach, nikde sa nevyťahujú."),
    array("name" => "Kristián C.", "text" => "Materiál je hladký na pokožke, žiadne nepríjemné švy."),
    array("name" => "Dávid V.", "text" => "Aj po celom dni nosenia všetko drží na mieste."),
    array("name" => "Miroslav L.", "text" => "Noriks boxerky pôsobia kvalitne hneď pri prvom dotyku."),
    array("name" => "Peter G.", "text" => "Nosím ich už týždne a nevznikajú žmolky ani vytiahnutý materiál."),
    array("name" => "Andrej B.", "text" => "Perfektný strih, kopírujú telo bez tlačenia."),
    array("name" => "Filip J.", "text" => "Nohavičky sa nevyhŕňajú nahor, veľké plus."),
    array("name" => "Nikolas R.", "text" => "Noriks boxerky sú moja prvá voľba zo zásuvky."),
    array("name" => "Matej S.", "text" => "Žiadne nepríjemné potenie, látka dobre dýcha."),
    array("name" => "Dominik K.", "text" => "Vyzerajú, že vydržia dlho. Švy sú pevné a precízne."),
    array("name" => "Ivan H.", "text" => "Výborný pomer ceny a kvality, lepšie než oveľa drahšie značky."),
    array("name" => "Viktor P.", "text" => "Pod nohavicami sa nevyhŕňajú, všetko zostáva na mieste."),
    array("name" => "Branislav N.", "text" => "Sedia výborne aj keď som medzi veľkosťami."),
    array("name" => "René T.", "text" => "Guma nestráca elasticitu ani po praní."),
    array("name" => "Andrej M.", "text" => "Ideálne do práce aj na tréning – značku už nemením."),
    array("name" => "Dino K.", "text" => "Pocit ako pyžamo, ale vyzerajú moderne."),
    array("name" => "Leon B.", "text" => "Pekne tvarujú bez voľného vzhľadu."),
    array("name" => "Darko Z.", "text" => "Materiál rýchlo schne, super na cestovanie."),
    array("name" => "Viktor H.", "text" => "Netlačia ani pri dlhom sedení v kancelárii."),
    array("name" => "Krištof F.", "text" => "Žiadne drsné etikety, všetko kvalitne spracované."),
    array("name" => "Tibor K.", "text" => "Nosím ich celý deň a večer sú stále pohodlné."),
    array("name" => "Boris V.", "text" => "Neotáčajú sa ani pod rifľami."),
    array("name" => "Mario Č.", "text" => "Strih pekne kopíruje nohy bez záhybov."),
    array("name" => "Štefan C.", "text" => "Kúpil som jeden pár a hneď objednal ďalšie tri."),
    array("name" => "Marek N.", "text" => "Farba zostáva sýta aj po mnohých praniach."),
    array("name" => "Daniel L.", "text" => "Žiadny nepríjemný zápach ani po náročnom dni."),
    array("name" => "Goran B.", "text" => "Nahradili všetky moje staré boxerky."),
    array("name" => "Željko R.", "text" => "Nikde netlačia a zároveň dobre držia."),
    array("name" => "Vedran M.", "text" => "Ideálne na leto, nelepi sa na pokožku."),
    array("name" => "Stanislav J.", "text" => "Švy sú hladké, nič nedrie ani pri dlhšej chôdzi."),
    array("name" => "Vladimír N.", "text" => "Látka je dostatočne hustá, ale stále ľahká."),
    array("name" => "Nino E.", "text" => "Držia všetko na mieste aj počas tréningu."),
    array("name" => "Samuel K.", "text" => "Konečne spodná bielizeň, ktorá neotravuje."),
    array("name" => "Igor B.", "text" => "Ani po sušičke sa nezrazili ani nedeformovali."),
    array("name" => "Ján T.", "text" => "Sedia výborne aj vyšším postavám."),
    array("name" => "Tvrtko G.", "text" => "Perfektný fit v páse aj na stehnách."),
    array("name" => "Boris R.", "text" => "Tak pohodlné, že ich skoro necítim."),
    array("name" => "Karol D.", "text" => "Do práce aj do fitka – zvládnu všetko."),
    array("name" => "Milan H.", "text" => "Guma nezanecháva stopy na pokožke."),
    array("name" => "Zoran P.", "text" => "Príjemné na dotyk, bez syntetického pocitu."),
    array("name" => "Dražen K.", "text" => "Prvé boxerky, ktoré sa mi nevyhŕňajú."),
    array("name" => "František M.", "text" => "Ideálny strih – ani úzke, ani voľné."),
    array("name" => "Nikolas H.", "text" => "Ráno si ich oblečiem a celý deň neriešim."),
    array("name" => "Róbert V.", "text" => "Skvelé aj na dlhé jazdy autom."),
    array("name" => "Marin J.", "text" => "Držia formu aj po mesiaci prania."),
    array("name" => "Toni P.", "text" => "Pod oblekom vyzerajú hladko."),
    array("name" => "Andrej K.", "text" => "Od kedy ich mám, iné už nenosím."),
    array("name" => "Lovro B.", "text" => "Mäkké, ale veľmi odolné."),
    array("name" => "Karol Z.", "text" => "Žiadne podráždenie ani v horúčave."),
    array("name" => "Zdeslav L.", "text" => "Najpohodlnejšie boxerky, aké som mal."),
    array("name" => "Viktor P.", "text" => "Ideálna dĺžka, netlačia v slabinách."),
    array("name" => "Martin G.", "text" => "Pôsobia ako prémiová značka za normálnu cenu."),
    array("name" => "Alan S.", "text" => "Švy takmer necítiť."),
    array("name" => "Kristián J.", "text" => "Nevytvárajú žmolky ani nezachytávajú chlpy."),
    array("name" => "Lukáš F.", "text" => "Perfektné boxerky na každý deň."),
    array("name" => "Mario R.", "text" => "Aj po tréningu všetko drží na mieste."),
    array("name" => "Andrej C.", "text" => "Príjemné prekvapenie – komfort 10/10."),
    array("name" => "Ivan O.", "text" => "Kúpil som viac párov a nosím len tieto."),
    array("name" => "Štefan V.", "text" => "Nevyhrňujú sa ani pod úzkymi nohavicami."),
    array("name" => "Dino L.", "text" => "Rýchlo schnú a nezadržiavajú vlhkosť."),
    array("name" => "Goran U.", "text" => "Ideálne pre ľudí, ktorí veľa sedia pri počítači."),
    array("name" => "Miroslav E.", "text" => "Aj po týždňoch vyzerajú ako nové."),
    array("name" => "Bruno Č.", "text" => "Jednoduché a mužné bez zbytočných vzorov."),
    array("name" => "Nikola K.", "text" => "Perfektná rovnováha medzi pohodlím a oporou."),
    array("name" => "Viktor J.", "text" => "Netlačia ani v páse ani na stehnách."),
    array("name" => "Srečko P.", "text" => "Ľahko sa perú a rýchlo schnú."),
    array("name" => "Leo M.", "text" => "Farby zodpovedajú fotografiám."),
    array("name" => "Damian D.", "text" => "Aj po hodinách v teple stále pohodlné."),
    array("name" => "Dorian S.", "text" => "Nevidno ich cez tenké nohavice."),
    array("name" => "Adrián K.", "text" => "Široká guma sa nepretáča."),
    array("name" => "René H.", "text" => "Počas dňa sa cítim výrazne pohodlnejšie."),
    array("name" => "Zlatko R.", "text" => "Dobré aj pre silnejšiu postavu."),
    array("name" => "Tomáš E.", "text" => "Bez problémov zvládnu prácu aj tréning."),
    array("name" => "Krištof L.", "text" => "Konečne spodná bielizeň bez neustáleho upravovania."),
    array("name" => "Nenad K.", "text" => "Som veľmi spokojný, určite objednám znova."),
    array("name" => "Dragan V.", "text" => "Nekĺžu dole, držia pás celý deň."),
    array("name" => "Slavomír T.", "text" => "Perfektná hustota materiálu."),
    array("name" => "Alberto N.", "text" => "Skvelé na každý deň aj cestovanie."),
    array("name" => "Zrinko B.", "text" => "Po praní žiadne deformácie."),
    array("name" => "Ilija S.", "text" => "Netlačia v slabinách, čo bol môj problém pri iných."),
    array("name" => "Mario L.", "text" => "Pohodlné aj počas aktívneho dňa."),
    array("name" => "Lovro Š.", "text" => "Nezarezávajú sa do bokov."),
    array("name" => "Željko K.", "text" => "Recenzie nepíšem často, ale tieto si to zaslúžia."),
    array("name" => "Andrej Ž.", "text" => "Posúvajú komfort na úplne inú úroveň."),
    array("name" => "Vladimír R.", "text" => "Keď ich skúsiš, iné už nechceš."),
    array("name" => "Goran Č.", "text" => "Rýchle doručenie a top produkt."),
    array("name" => "Viliam S.", "text" => "Perfektne priliehajú, nohavičky sa nevyhŕňajú."),
    array("name" => "Oleg T.", "text" => "Tak mäkké, že ich skoro necítim."),
    array("name" => "Štefan I.", "text" => "Celodenné nosenie bez nepohodlia."),
    array("name" => "Karol H.", "text" => "Guma je výborná, nepretáča sa."),
    array("name" => "Darin P.", "text" => "Po praní rovnaké ako nové."),
    array("name" => "Adrián V.", "text" => "Priedušný a pohodlný materiál."),
    array("name" => "Leon M.", "text" => "Ideálna dĺžka."),
    array("name" => "Augustín J.", "text" => "Stali sa mojou prvou voľbou."),
    array("name" => "Kristián U.", "text" => "Žiadne potenie ani po tréningu."),
    array("name" => "Dejan T.", "text" => "Čakal som dobré, ale toto je top."),
    array("name" => "Juraj A.", "text" => "Mäkké a pevné zároveň."),
    array("name" => "Darko S.", "text" => "Nevyhrňujú sa."),
    array("name" => "Benedikt K.", "text" => "Konečne boxerky bez tlačenia."),
    array("name" => "Loren P.", "text" => "Veľmi kvalitný materiál."),
    array("name" => "Ignác R.", "text" => "Veľká spokojnosť, kupujem znova."),
    array("name" => "Marin D.", "text" => "Veľmi príjemné na pokožke."),
    array("name" => "Miron B.", "text" => "Švy sú perfektne spracované."),
    array("name" => "René M.", "text" => "Do kancelárie aj na tréning."),
    array("name" => "Teo Z.", "text" => "Iné boxerky už nechcem nosiť."),
    array("name" => "Branislav Š.", "text" => "Guma drží, ale netlačí."),
    array("name" => "Valentino R.", "text" => "Nezadržiavajú vlhkosť."),
    array("name" => "Patrik L.", "text" => "Pohodlné aj po hodinách nosenia."),
    array("name" => "Tomáš U.", "text" => "Bez podráždenia aj v horúčave."),
    array("name" => "Mario Š.", "text" => "Veľmi kvalitné spracovanie."),
    array("name" => "Nikola D.", "text" => "Nehýbu sa počas cvičenia."),
    array("name" => "Vito P.", "text" => "Aj po 10 praniach ako nové."),
    array("name" => "Zdenko T.", "text" => "Boxerky, ktoré dávajú zmysel."),
    array("name" => "Lovre K.", "text" => "Materiál nedráždi pokožku."),
    array("name" => "Ernest B.", "text" => "Skvelé na každý deň."),
    array("name" => "Roman V.", "text" => "Perfektne sedia mojej postave."),
    array("name" => "Marek G.", "text" => "Dobré v zime aj v lete."),
    array("name" => "Kristo H.", "text" => "Nevyzerajú opotrebovane ani po mesiaci."),
    array("name" => "Tibor A.", "text" => "Strih mi perfektne sedí."),
    array("name" => "Fabian S.", "text" => "Pohodlné aj počas dlhého šoférovania."),
    array("name" => "Damian K.", "text" => "Najlepšie boxerky, aké som kúpil."),
    array("name" => "Sebastián M.", "text" => "Materiál prémiovej kvality."),
    array("name" => "Zoran U.", "text" => "Netlačia stehná."),
    array("name" => "Krištof B.", "text" => "Všetko drží na mieste."),
    array("name" => "Dávid P.", "text" => "Bez nepohodlia aj po dlhom nosení."),
    array("name" => "Timotej L.", "text" => "Ideálne na každodenné používanie."),
    array("name" => "Ognjen R.", "text" => "Nevyhrňujú sa počas dňa."),
    array("name" => "Slavko I.", "text" => "Maximálne pohodlie."),
    array("name" => "Ján S.", "text" => "Výborná rovnováha pohodlia a opory."),
    array("name" => "Matej V.", "text" => "Prirodzený pocit bez kĺzania."),
    array("name" => "Ivan P.", "text" => "Držia tvar."),
    array("name" => "Julian D.", "text" => "Materiál je veľmi príjemný."),
    array("name" => "Matúš H.", "text" => "Guma sa neláme ani nekrúti."),
    array("name" => "Vito Č.", "text" => "Kvalita lepšia než som čakal."),
    array("name" => "Bono K.", "text" => "Nevedel som, že boxerky môžu byť také dobré."),
    array("name" => "Marek U.", "text" => "Výborná ventilácia."),
    array("name" => "Ladislav F.", "text" => "Žiadne trenie ani pri dlhej chôdzi."),
    array("name" => "Miroslav T.", "text" => "Pohodlné aj vo veľkom teple."),
    array("name" => "Viliam P.", "text" => "Najlepšie pre moju postavu."),
    array("name" => "Adem S.", "text" => "Materiál výborne dýcha."),
    array("name" => "Harun J.", "text" => "Veľmi ľahké a priedušné."),
    array("name" => "Noah M.", "text" => "Farba drží."),
    array("name" => "Tomáš Č.", "text" => "Pohodlné aj pod rifľami."),
    array("name" => "Valentín L.", "text" => "Nečakal som taký dobrý pocit."),
    array("name" => "Dávid S.", "text" => "Naozaj výborné boxerky."),
    array("name" => "Leon N.", "text" => "Nosím ich každý deň."),
    array("name" => "Viktor J.", "text" => "Žiadne záhyby ani krútenie."),
    array("name" => "Dino P.", "text" => "Dostal som viac než som čakal."),
    array("name" => "František S.", "text" => "Výborné aj na bicykel."),
    array("name" => "Erik R.", "text" => "Určite odporúčam."),
    array("name" => "Silvio M.", "text" => "Materiál zostáva hladký."),
    array("name" => "Zlatan G.", "text" => "Nevyhrňujú sa."),
    array("name" => "Dalibor S.", "text" => "Ideálne pre citlivú pokožku."),
    array("name" => "Gorjan P.", "text" => "Guma nezanecháva stopy."),
    array("name" => "Bojan T.", "text" => "Veľká spokojnosť s pohodlím."),
    array("name" => "Alan F.", "text" => "Totálny game-changer."),
    array("name" => "Štefan L.", "text" => "Materiál rýchlo schne."),
    array("name" => "Marek Ž.", "text" => "Pod nohavicami sa nekrčia."),
    array("name" => "Vladimír Š.", "text" => "Bez nepríjemného zápachu."),
    array("name" => "Lukáš R.", "text" => "Konečne boxerky, ktoré sedia."),
    array("name" => "Filip U.", "text" => "Ľahko sa perú a držia tvar."),
    array("name" => "Boris K.", "text" => "Mäkké a odolné."),
    array("name" => "Ivan X.", "text" => "Najlepšie v tejto cenovej kategórii."),
    array("name" => "Bruno V.", "text" => "Naozaj sa nevyhŕňajú."),
    array("name" => "Andrej K.", "text" => "Veľká spokojnosť s materiálom."),
    array("name" => "Sandi B.", "text" => "Nedráždia pokožku."),
    array("name" => "Kevin S.", "text" => "Nosím ich každý deň."),
    array("name" => "Matias P.", "text" => "Prémiový pocit."),
    array("name" => "Martin V.", "text" => "Aj po mesiaci ako nové."),
    array("name" => "Oskar L.", "text" => "Pevné a flexibilné."),
    array("name" => "Dino J.", "text" => "Netlačia ani pri cvičení."),
    array("name" => "Nikola U.", "text" => "Jednoducho perfektné."),
    array("name" => "Sven M.", "text" => "Guma sa neroluje."),
    array("name" => "Róbert P.", "text" => "Jedny z najpohodlnejších boxeriek."),
    array("name" => "Karol B.", "text" => "Určite odporúčam."),
    array("name" => "Tomáš S.", "text" => "Materiál skutočne dýcha."),
    array("name" => "Marek K.", "text" => "Výborné aj na šport."),
    array("name" => "Dávid Z.", "text" => "Nemám žiadne výhrady."),
    array("name" => "Daniel F.", "text" => "Stoja za každé euro."),
    array("name" => "Miroslav K.", "text" => "Nosím ich denne — perfektné."),
    array("name" => "Sebastián R.", "text" => "Bez chyby. Kupujem znova.")
);
?>
